/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import java.awt.Color;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.Image;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.nio.file.Files;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author massi
 */
public class Interfaz extends javax.swing.JFrame {

    int xMouse, yMouse;

    private ImageIcon imagen;
    private Icon icono;

    public Interfaz() {
        initComponents();
        tab1.setBackground(Color.black);
        this.setLocationRelativeTo(this);

        this.pintarImagen(this.Icono1, "src/Img/Compras2.gif");
        this.pintarImagen(this.Icono2, "src/Img/propiedades.gif");
        this.pintarImagen(this.ImgArch, "src/Img/Archivo.png");
        this.pintarImagen(this.ImgProy, "src/Img/Proyectar.png");
        this.pintarImagen(this.ImgVal, "src/Img/Valor.png");
        this.pintarImagen(this.ImgMarc, "src/Img/Marcar.png");
        this.pintarImagen(this.ImgPresen, "src/Img/Presentacion.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        Inicio = new javax.swing.JPanel();
        Pagina1 = new javax.swing.JPanel();
        exitBtn1 = new javax.swing.JPanel();
        exitTxt1 = new javax.swing.JLabel();
        Icono1 = new javax.swing.JLabel();
        Icono2 = new javax.swing.JLabel();
        TextBienv = new javax.swing.JLabel();
        Barrapg_1 = new javax.swing.JPanel();
        Barrapg_2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Textpag1 = new javax.swing.JTextArea();
        Pagina2 = new javax.swing.JPanel();
        exitBtn2 = new javax.swing.JPanel();
        exitTxt2 = new javax.swing.JLabel();
        BtnRed = new javax.swing.JButton();
        BtnMost = new javax.swing.JButton();
        BtnT = new javax.swing.JButton();
        Barrapg_3 = new javax.swing.JPanel();
        Barrapg_4 = new javax.swing.JPanel();
        ImgArch = new javax.swing.JLabel();
        ImgProy = new javax.swing.JLabel();
        ImgVal = new javax.swing.JLabel();
        BtnSelec = new javax.swing.JButton();
        BtnVer = new javax.swing.JButton();
        ImgMarc = new javax.swing.JLabel();
        ImgPresen = new javax.swing.JLabel();
        Pagina3 = new javax.swing.JPanel();
        exitBtn3 = new javax.swing.JPanel();
        exitTxt3 = new javax.swing.JLabel();
        Barrapg_5 = new javax.swing.JPanel();
        Barrapg_6 = new javax.swing.JPanel();
        Pagina4 = new javax.swing.JPanel();
        exitBtn4 = new javax.swing.JPanel();
        exitTxt4 = new javax.swing.JLabel();
        Barrapg_7 = new javax.swing.JPanel();
        Barrapg_8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAbout = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        tab1.setBackground(new java.awt.Color(102, 102, 102));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab2.setBackground(new java.awt.Color(102, 102, 102));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Services");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab3.setBackground(new java.awt.Color(102, 102, 102));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(82, 82, 82))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab4.setBackground(new java.awt.Color(102, 102, 102));
        tab4.setForeground(new java.awt.Color(102, 102, 102));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("About");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(89, 89, 89))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Titulo.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText(" SUCURSALES");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Nombre.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 153, 0));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("MetroMarket");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Nombre)
                .addGap(18, 18, 18)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Inicio.setBackground(new java.awt.Color(153, 153, 153));
        Inicio.setLayout(new javax.swing.OverlayLayout(Inicio));

        Pagina1.setBackground(new java.awt.Color(255, 255, 255));
        Pagina1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pagina1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Pagina1MouseDragged(evt);
            }
        });
        Pagina1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pagina1MousePressed(evt);
            }
        });

        exitBtn1.setBackground(new java.awt.Color(255, 153, 51));

        exitTxt1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt1.setText("X");
        exitTxt1.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtn1Layout = new javax.swing.GroupLayout(exitBtn1);
        exitBtn1.setLayout(exitBtn1Layout);
        exitBtn1Layout.setHorizontalGroup(
            exitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtn1Layout.setVerticalGroup(
            exitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Icono1.setBackground(new java.awt.Color(255, 153, 0));
        Icono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Icono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextBienv.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        TextBienv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBienv.setText("¡Bienvenido!");

        Barrapg_1.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_1Layout = new javax.swing.GroupLayout(Barrapg_1);
        Barrapg_1.setLayout(Barrapg_1Layout);
        Barrapg_1Layout.setHorizontalGroup(
            Barrapg_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        Barrapg_1Layout.setVerticalGroup(
            Barrapg_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Barrapg_2.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_2Layout = new javax.swing.GroupLayout(Barrapg_2);
        Barrapg_2.setLayout(Barrapg_2Layout);
        Barrapg_2Layout.setHorizontalGroup(
            Barrapg_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Barrapg_2Layout.setVerticalGroup(
            Barrapg_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Textpag1.setColumns(20);
        Textpag1.setRows(5);
        Textpag1.setText("Bienvenido a nuestro exclusivo programa de planificación estratégica \npara la ubicación de sucursales. Estamos emocionados de que te unas \na este proyecto innovador que tiene como objetivo optimizar la \npresencia de una reconocida cadena de supermercados en Sudamérica. \n\n\n");
        jScrollPane2.setViewportView(Textpag1);

        javax.swing.GroupLayout Pagina1Layout = new javax.swing.GroupLayout(Pagina1);
        Pagina1.setLayout(Pagina1Layout);
        Pagina1Layout.setHorizontalGroup(
            Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barrapg_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina1Layout.createSequentialGroup()
                .addComponent(Barrapg_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Pagina1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Icono2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(TextBienv, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icono1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Pagina1Layout.setVerticalGroup(
            Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pagina1Layout.createSequentialGroup()
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barrapg_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pagina1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(TextBienv))
                    .addGroup(Pagina1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Icono2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Icono1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Barrapg_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Icono1.getAccessibleContext().setAccessibleName("Icono");

        Inicio.add(Pagina1);

        Pagina2.setBackground(new java.awt.Color(255, 153, 0));
        Pagina2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Pagina2MouseDragged(evt);
            }
        });
        Pagina2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pagina2MousePressed(evt);
            }
        });

        exitBtn2.setBackground(new java.awt.Color(255, 153, 0));
        exitBtn2.setPreferredSize(new java.awt.Dimension(40, 40));

        exitTxt2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt2.setText("X");
        exitTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtn2Layout = new javax.swing.GroupLayout(exitBtn2);
        exitBtn2.setLayout(exitBtn2Layout);
        exitBtn2Layout.setHorizontalGroup(
            exitBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtn2Layout.setVerticalGroup(
            exitBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BtnRed.setBackground(new java.awt.Color(51, 51, 51));
        BtnRed.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnRed.setForeground(new java.awt.Color(255, 255, 255));
        BtnRed.setText("Cargar Red");
        BtnRed.setBorder(null);
        BtnRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRedMouseExited(evt);
            }
        });
        BtnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRedActionPerformed(evt);
            }
        });

        BtnMost.setBackground(new java.awt.Color(51, 51, 51));
        BtnMost.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnMost.setForeground(new java.awt.Color(255, 255, 255));
        BtnMost.setText("Mostrar Grafo");
        BtnMost.setBorder(null);
        BtnMost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMostMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMostMouseExited(evt);
            }
        });
        BtnMost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostActionPerformed(evt);
            }
        });

        BtnT.setBackground(new java.awt.Color(51, 51, 51));
        BtnT.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnT.setForeground(new java.awt.Color(255, 255, 255));
        BtnT.setText("Establecer T");
        BtnT.setBorder(null);
        BtnT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnTMouseExited(evt);
            }
        });
        BtnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTActionPerformed(evt);
            }
        });

        Barrapg_3.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_3Layout = new javax.swing.GroupLayout(Barrapg_3);
        Barrapg_3.setLayout(Barrapg_3Layout);
        Barrapg_3Layout.setHorizontalGroup(
            Barrapg_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Barrapg_3Layout.setVerticalGroup(
            Barrapg_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Barrapg_4.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_4Layout = new javax.swing.GroupLayout(Barrapg_4);
        Barrapg_4.setLayout(Barrapg_4Layout);
        Barrapg_4Layout.setHorizontalGroup(
            Barrapg_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Barrapg_4Layout.setVerticalGroup(
            Barrapg_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        ImgArch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ImgProy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ImgVal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BtnSelec.setBackground(new java.awt.Color(51, 51, 51));
        BtnSelec.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnSelec.setForeground(new java.awt.Color(255, 255, 255));
        BtnSelec.setText("Colocar Sucursal");
        BtnSelec.setBorder(null);
        BtnSelec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSelecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSelecMouseExited(evt);
            }
        });
        BtnSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelecActionPerformed(evt);
            }
        });

        BtnVer.setBackground(new java.awt.Color(51, 51, 51));
        BtnVer.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        BtnVer.setForeground(new java.awt.Color(255, 255, 255));
        BtnVer.setText("Ver cobertura ");
        BtnVer.setBorder(null);
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pagina2Layout = new javax.swing.GroupLayout(Pagina2);
        Pagina2.setLayout(Pagina2Layout);
        Pagina2Layout.setHorizontalGroup(
            Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barrapg_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina2Layout.createSequentialGroup()
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Barrapg_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Pagina2Layout.createSequentialGroup()
                        .addContainerGap(304, Short.MAX_VALUE)
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImgMarc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImgPresen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSelec, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Pagina2Layout.createSequentialGroup()
                                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ImgArch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ImgProy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMost, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Pagina2Layout.createSequentialGroup()
                                .addComponent(ImgVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnT, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Pagina2Layout.setVerticalGroup(
            Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina2Layout.createSequentialGroup()
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pagina2Layout.createSequentialGroup()
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Barrapg_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pagina2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(BtnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ImgMarc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(ImgArch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pagina2Layout.createSequentialGroup()
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ImgProy, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMost, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnVer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImgVal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(Pagina2Layout.createSequentialGroup()
                        .addComponent(ImgPresen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Barrapg_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Inicio.add(Pagina2);

        Pagina3.setBackground(new java.awt.Color(255, 153, 0));
        Pagina3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Pagina3MouseDragged(evt);
            }
        });
        Pagina3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pagina3MousePressed(evt);
            }
        });

        exitBtn3.setBackground(new java.awt.Color(255, 153, 0));
        exitBtn3.setPreferredSize(new java.awt.Dimension(40, 40));

        exitTxt3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt3.setText("X");
        exitTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtn3Layout = new javax.swing.GroupLayout(exitBtn3);
        exitBtn3.setLayout(exitBtn3Layout);
        exitBtn3Layout.setHorizontalGroup(
            exitBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtn3Layout.setVerticalGroup(
            exitBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Barrapg_5.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_5Layout = new javax.swing.GroupLayout(Barrapg_5);
        Barrapg_5.setLayout(Barrapg_5Layout);
        Barrapg_5Layout.setHorizontalGroup(
            Barrapg_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Barrapg_5Layout.setVerticalGroup(
            Barrapg_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Barrapg_6.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_6Layout = new javax.swing.GroupLayout(Barrapg_6);
        Barrapg_6.setLayout(Barrapg_6Layout);
        Barrapg_6Layout.setHorizontalGroup(
            Barrapg_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        Barrapg_6Layout.setVerticalGroup(
            Barrapg_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pagina3Layout = new javax.swing.GroupLayout(Pagina3);
        Pagina3.setLayout(Pagina3Layout);
        Pagina3Layout.setHorizontalGroup(
            Pagina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pagina3Layout.createSequentialGroup()
                .addComponent(Barrapg_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Barrapg_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Pagina3Layout.setVerticalGroup(
            Pagina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pagina3Layout.createSequentialGroup()
                .addGroup(Pagina3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Barrapg_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(Barrapg_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Inicio.add(Pagina3);

        Pagina4.setBackground(new java.awt.Color(255, 153, 0));
        Pagina4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Pagina4MouseDragged(evt);
            }
        });
        Pagina4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pagina4MousePressed(evt);
            }
        });

        exitBtn4.setBackground(new java.awt.Color(255, 153, 0));
        exitBtn4.setPreferredSize(new java.awt.Dimension(40, 40));

        exitTxt4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        exitTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt4.setText("X");
        exitTxt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtn4Layout = new javax.swing.GroupLayout(exitBtn4);
        exitBtn4.setLayout(exitBtn4Layout);
        exitBtn4Layout.setHorizontalGroup(
            exitBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtn4Layout.setVerticalGroup(
            exitBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Barrapg_7.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_7Layout = new javax.swing.GroupLayout(Barrapg_7);
        Barrapg_7.setLayout(Barrapg_7Layout);
        Barrapg_7Layout.setHorizontalGroup(
            Barrapg_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        Barrapg_7Layout.setVerticalGroup(
            Barrapg_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Barrapg_8.setBackground(new java.awt.Color(51, 51, 51));
        Barrapg_8.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Barrapg_8Layout = new javax.swing.GroupLayout(Barrapg_8);
        Barrapg_8.setLayout(Barrapg_8Layout);
        Barrapg_8Layout.setHorizontalGroup(
            Barrapg_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Barrapg_8Layout.setVerticalGroup(
            Barrapg_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        TextAbout.setBackground(new java.awt.Color(102, 102, 102));
        TextAbout.setColumns(20);
        TextAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TextAbout.setForeground(new java.awt.Color(255, 255, 255));
        TextAbout.setRows(5);
        TextAbout.setText("Modelo Geográfico\nCada parada de transporte se considera el centro de una zona comercial, dentro de un radio de hasta t paradas. Una sucursal cubre una zona si está a no más de t paradas de una parada con sucursal.\n\nFuncionalidades del Programa\nCargar Red de Transporte: Permite cargar y reemplazar redes de transporte desde archivos.\n\nMostrar Grafo: Visualiza la red de transporte usando GraphStream.\n\nEstablecer Valor de t: Posibilidad de cambiar el valor de t en cualquier momento para evaluar diferentes escenarios.\n\nColocar Sucursal: Seleccionar paradas para ubicar sucursales y ver la cobertura comercial.\n\nVer Cobertura de Sucursal: Usar DFS o BFS para mostrar paradas alcanzables desde una sucursal.\n\nRevisar Cobertura Total: Evaluar si las sucursales cubren toda la ciudad y sugerir nuevas ubicaciones si es necesario.\n\nAgregar Línea: Añadir nuevas líneas a la red para evaluar la cobertura futura.\n");
        jScrollPane1.setViewportView(TextAbout);

        javax.swing.GroupLayout Pagina4Layout = new javax.swing.GroupLayout(Pagina4);
        Pagina4.setLayout(Pagina4Layout);
        Pagina4Layout.setHorizontalGroup(
            Pagina4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barrapg_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina4Layout.createSequentialGroup()
                .addGroup(Pagina4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barrapg_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Pagina4Layout.setVerticalGroup(
            Pagina4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pagina4Layout.createSequentialGroup()
                .addGroup(Pagina4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Barrapg_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Barrapg_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Inicio.add(Pagina4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        Pagina1.setVisible(true);
        Pagina2.setVisible(false);
        Pagina3.setVisible(false);
        Pagina4.setVisible(false);
        tab1.setBackground(Color.black);
        tab2.setBackground(new Color(102, 102, 102));
        tab3.setBackground(new Color(102, 102, 102));
        tab4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        Pagina2.setVisible(true);
        Pagina1.setVisible(false);
        Pagina3.setVisible(false);
        Pagina4.setVisible(false);
        tab2.setBackground(Color.black);
        tab1.setBackground(new Color(102, 102, 102));
        tab3.setBackground(new Color(102, 102, 102));
        tab4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        Pagina3.setVisible(true);
        Pagina2.setVisible(false);
        Pagina1.setVisible(false);
        Pagina4.setVisible(false);
        tab3.setBackground(Color.black);
        tab2.setBackground(new Color(102, 102, 102));
        tab1.setBackground(new Color(102, 102, 102));
        tab4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        Pagina4.setVisible(true);
        Pagina3.setVisible(false);
        Pagina2.setVisible(false);
        Pagina1.setVisible(false);
        tab4.setBackground(Color.black);
        tab2.setBackground(new Color(102, 102, 102));
        tab3.setBackground(new Color(102, 102, 102));
        tab1.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_tab4MouseClicked

    private void Pagina1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Pagina1MousePressed

    private void Pagina1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina1MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse); // Direccion del eje X y eje Y del mouse 
    }//GEN-LAST:event_Pagina1MouseDragged

    private void exitTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseClicked
        System.exit(0); // Salida del programa
    }//GEN-LAST:event_exitTxt1MouseClicked

    private void exitTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseEntered
        exitBtn1.setBackground(Color.red);// Coloca el color rojo al seleccionarlo
        exitTxt1.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt1MouseEntered

    private void exitTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseExited
        exitBtn1.setBackground(new Color(255, 153, 51));// Devuelve el color del background
        exitTxt1.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt1MouseExited

    private void Pagina2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Pagina2MousePressed

    private void Pagina2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Pagina2MouseDragged

    private void exitTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxt2MouseClicked

    private void exitTxt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseEntered
        exitBtn2.setBackground(Color.red);
        exitTxt2.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt2MouseEntered

    private void exitTxt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt2MouseExited
        exitBtn2.setBackground(new Color(255, 153, 51));
        exitTxt2.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt2MouseExited

    private void exitTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxt3MouseClicked

    private void exitTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseEntered
        exitBtn3.setBackground(Color.red);
        exitTxt3.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt3MouseEntered

    private void exitTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt3MouseExited
        exitBtn3.setBackground(new Color(255, 153, 51));
        exitTxt3.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt3MouseExited

    private void Pagina3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Pagina3MousePressed

    private void Pagina3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Pagina3MouseDragged

    private void exitTxt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxt4MouseClicked

    private void exitTxt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt4MouseEntered
        exitBtn4.setBackground(Color.red);
        exitTxt4.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt4MouseEntered

    private void exitTxt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt4MouseExited
        exitBtn4.setBackground(new Color(255, 153, 51));
        exitTxt4.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt4MouseExited

    private void Pagina4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Pagina4MousePressed

    private void Pagina4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pagina4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Pagina4MouseDragged

    private void BtnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRedActionPerformed
        var chooser = new JFileChooser();
        chooser.showOpenDialog(null);

        var file = chooser.getSelectedFile();

        if (file != null) {
            try {
                var nombre = file.getName();
                if (nombre == "caracas") {
                    Grafo.ObtenerInstancia().T = 3;
                } else if (nombre == "bogota") {
                    Grafo.ObtenerInstancia().T = 10;
                }

                var contenido = new String(Files.readAllBytes(file.toPath()));

                JsonParser parser = new JsonParser();
                var element = parser.parse(contenido);
                var sistemaDeTransporteObjecto = element.getAsJsonObject().entrySet();
                var sistemaDeTransporte = sistemaDeTransporteObjecto.iterator().next();
                Grafo.ObtenerInstancia().nombreSistemaDeTransporte = sistemaDeTransporte.getKey();

                var lineas = sistemaDeTransporte.getValue().getAsJsonArray();
                for (JsonElement lineaElement : lineas) {
                    var lineaObjeto = lineaElement.getAsJsonObject().entrySet();
                    var linea = lineaObjeto.iterator().next();
                    String nombreDeLinea = linea.getKey();

                    var estacionesArray = linea.getValue().getAsJsonArray();

                    NodoGrafo ultimoNodoLeido = null;
                    for (JsonElement estacionObject : estacionesArray) {
                        if (estacionObject.isJsonPrimitive()) {
                            // Manejar estación simple
                            var estacion = estacionObject.getAsString();
                            if (ultimoNodoLeido == null) {
                                ultimoNodoLeido = new NodoGrafo(new Lista(), estacion, nombreDeLinea, Grafo.ObtenerInstancia().nodos.getSize());
                                Grafo.ObtenerInstancia().nodos.Agregar(ultimoNodoLeido);
                            } else {
                                var nuevoNodo = new NodoGrafo(new Lista(), estacion, nombreDeLinea, Grafo.ObtenerInstancia().nodos.getSize());
                                ultimoNodoLeido.getVecinos().Agregar(nuevoNodo);
                                nuevoNodo.getVecinos().Agregar(ultimoNodoLeido);
                                Grafo.ObtenerInstancia().nodos.Agregar(nuevoNodo);
                                ultimoNodoLeido = nuevoNodo;
                            }
                        } else if (estacionObject.isJsonObject()) {
                            // Manejar objeto con clave-valor
                            var objetoEstacion = estacionObject.getAsJsonObject();
                            // Obtener las claves del objeto
                            for (String clave : objetoEstacion.keySet()) {
                                String vecino = objetoEstacion.get(clave).getAsString();

                                // Crear nodo para la estación
                                var nuevoNodo = new NodoGrafo(new Lista(), clave, nombreDeLinea, Grafo.ObtenerInstancia().nodos.getSize());
                                Grafo.ObtenerInstancia().nodos.Agregar(nuevoNodo);

                                // Conectar nodos
                                if (ultimoNodoLeido != null) {
                                    ultimoNodoLeido.getVecinos().Agregar(nuevoNodo);
                                    nuevoNodo.getVecinos().Agregar(ultimoNodoLeido);
                                }
                                ultimoNodoLeido = nuevoNodo;

                                // Manejar el vecino
                                var vecinoNodo = new NodoGrafo(new Lista(), vecino, nombreDeLinea, Grafo.ObtenerInstancia().nodos.getSize());
                                Grafo.ObtenerInstancia().nodos.Agregar(vecinoNodo);
                                nuevoNodo.getVecinos().Agregar(vecinoNodo);
                                vecinoNodo.getVecinos().Agregar(nuevoNodo);
                            }
                        }
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        var aux = Grafo.ObtenerInstancia().nodos.getHead();

        while (aux != null) {
            System.out.print("Estacion: ");
            System.out.print(aux.getValor().getNombreEstacion());

            System.out.print(aux.getValor().getIndice());

            System.out.println();

            aux = aux.getNext();
        }
    }//GEN-LAST:event_BtnRedActionPerformed

    private void BtnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTActionPerformed

        String s = (String) JOptionPane.showInputDialog(
                this,
                "\n Introduzca el valor de t \n"
                + "",
                "",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "");

        try {

            int number = Integer.parseInt(s);
            if (number <= 0) {
                JOptionPane.showMessageDialog(this, "El número tiene que ser mayor que cero");
                return;
            }
            Grafo.ObtenerInstancia().T = number;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número valido");

        }


    }//GEN-LAST:event_BtnTActionPerformed

    private void BtnMostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostActionPerformed

// Configurar el sistema para usar GraphStream con Swing
        System.setProperty("org.graphstream.ui", "swing");

        // Crear un nuevo grafo
        Graph graph = new SingleGraph("Grafo");

        // Obtener la instancia del grafo
        Grafo grafo = Grafo.ObtenerInstancia();
        var aux = grafo.nodos.getHead();

        // Recorrer los nodos del grafo
        while (aux != null) {
            String estacion = aux.getValor().getNombreEstacion();

            // Verificar si el nodo ya existe
            if (graph.getNode(estacion) == null) {
                graph.addNode(estacion);
            }

            // Establecer el nombre del nodo como atributo
            graph.getNode(estacion).setAttribute("ui.label", estacion);
            // Establecer la posición de la etiqueta debajo del nodo
            graph.getNode(estacion).setAttribute("ui.label.position", "bottom");
            if (aux.getValor().getSucursal()) {
                graph.getNode(estacion).setAttribute("ui.style", "fill-color: red;");
            }

            var aux2 = aux.getValor().getVecinos().getHead();
            // Recorrer los vecinos de cada nodo
            while (aux2 != null) {
                String vecino = aux2.getValor().getNombreEstacion();

                // Verificar si el nodo vecino ya existe
                if (graph.getNode(vecino) == null) {
                    graph.addNode(vecino);
                }

                // Verificar si la arista ya existe
                if (graph.getEdge(estacion + "-" + vecino) == null && graph.getEdge(vecino + "-" + estacion) == null) {
                    graph.addEdge(estacion + "-" + vecino, estacion, vecino);
                }

                aux2 = aux2.getNext();
            }

            aux = aux.getNext();
        }

        Viewer viewer = graph.display();
        viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.HIDE_ONLY);


    }//GEN-LAST:event_BtnMostActionPerformed

    private void BtnMostMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMostMouseEntered
        BtnMost.setBackground(Color.white);
        BtnMost.setForeground(Color.black);
    }//GEN-LAST:event_BtnMostMouseEntered

    private void BtnMostMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMostMouseExited
        BtnMost.setBackground(new Color(51, 51, 51));
        BtnMost.setForeground(Color.white);
    }//GEN-LAST:event_BtnMostMouseExited

    private void BtnRedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRedMouseEntered
        BtnRed.setBackground(Color.white);
        BtnRed.setForeground(Color.black);
    }//GEN-LAST:event_BtnRedMouseEntered

    private void BtnRedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRedMouseExited
        BtnRed.setBackground(new Color(51, 51, 51));
        BtnRed.setForeground(Color.white);
    }//GEN-LAST:event_BtnRedMouseExited

    private void BtnTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTMouseEntered
        BtnT.setBackground(Color.white);
        BtnT.setForeground(Color.black);
    }//GEN-LAST:event_BtnTMouseEntered

    private void BtnTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTMouseExited
        BtnT.setBackground(new Color(51, 51, 51));
        BtnT.setForeground(Color.white);
    }//GEN-LAST:event_BtnTMouseExited

    private void BtnSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelecActionPerformed
        String paradaNombre = (String) JOptionPane.showInputDialog(
                this,
                "\n Ingrese su sucursal \n"
                + "",
                "",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                "");
        Grafo grafo = Grafo.ObtenerInstancia();
        var aux = grafo.nodos.getHead();

        // Recorrer los nodos del grafo
        while (aux != null) {
            String estacion = aux.getValor().getNombreEstacion();
            if (estacion.toLowerCase().equals(paradaNombre.toLowerCase())) {
                if (aux.getValor().getSucursal() == true) {
                    JOptionPane.showMessageDialog(this, "Se deseleccionó esta parada como sucursal");
                    aux.getValor().setSucursal(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Se seleccionó esta parada como sucursal");
                    aux.getValor().setSucursal(true);
                }
                return;
            }
            aux = aux.getNext();
        }
        JOptionPane.showMessageDialog(this, "No se encontró la parada");


    }//GEN-LAST:event_BtnSelecActionPerformed

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed

        var grafo = Grafo.ObtenerInstancia();
        if (grafo.getT() == 0) {
            JOptionPane.showMessageDialog(this, "No se puede cubrir ninguna sucursal si T = 0");
            return;
        }
        var sucursales = new Lista<NodoGrafo>();
        var aux = grafo.nodos.getHead();
        while (aux != null) {
            if (aux.getValor().getSucursal()) {
                sucursales.Agregar(aux.getValor());
            }
            aux = aux.getNext();
        }
        if (sucursales.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No hay sucursales");
            return;
        }

        Object[] options = {"Profundidad", "Anchura", "Cancelar"};

        int choice = JOptionPane.showOptionDialog(
                this,
                "Do you want to proceed?",
                "Custom Options",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[2]
        );

        if (choice == JOptionPane.YES_OPTION) {

            JOptionPane.showMessageDialog(this, "Buscando por profundidad...");
            boolean visited[] = new boolean[grafo.nodos.getSize()];
            for (var v : visited) {
                v = false;
            }
            var auxSucursales = sucursales.getHead();
            while (auxSucursales != null) {
                busquedaporprofundidad(visited, auxSucursales.getValor());

                auxSucursales = auxSucursales.getNext();
            }

        } else if (choice == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Buscando por anchura...");

        } else {
            JOptionPane.showMessageDialog(this, "Cancelado.");
        }

    }//GEN-LAST:event_BtnVerActionPerformed

    private void BtnSelecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSelecMouseEntered
        BtnSelec.setBackground(Color.white);
        BtnSelec.setForeground(Color.black);
    }//GEN-LAST:event_BtnSelecMouseEntered

    private void BtnSelecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSelecMouseExited
        BtnSelec.setBackground(new Color(51, 51, 51));
        BtnSelec.setForeground(Color.white);
    }//GEN-LAST:event_BtnSelecMouseExited

    public void busquedaporprofundidad(boolean[] visited, NodoGrafo vertice) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        Grafo.ObtenerInstancia().nodos = new Lista<NodoGrafo>();
        Grafo.ObtenerInstancia().esNulo = true;
        Grafo.ObtenerInstancia().nombreSistemaDeTransporte = "";

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    private void pintarImagen(JLabel lb1, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lb1.getWidth(),
                        lb1.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        lb1.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barrapg_1;
    private javax.swing.JPanel Barrapg_2;
    private javax.swing.JPanel Barrapg_3;
    private javax.swing.JPanel Barrapg_4;
    private javax.swing.JPanel Barrapg_5;
    private javax.swing.JPanel Barrapg_6;
    private javax.swing.JPanel Barrapg_7;
    private javax.swing.JPanel Barrapg_8;
    private javax.swing.JButton BtnMost;
    private javax.swing.JButton BtnRed;
    private javax.swing.JButton BtnSelec;
    private javax.swing.JButton BtnT;
    private javax.swing.JButton BtnVer;
    private javax.swing.JLabel Icono1;
    private javax.swing.JLabel Icono2;
    private javax.swing.JLabel ImgArch;
    private javax.swing.JLabel ImgMarc;
    private javax.swing.JLabel ImgPresen;
    private javax.swing.JLabel ImgProy;
    private javax.swing.JLabel ImgVal;
    private javax.swing.JPanel Inicio;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Pagina1;
    private javax.swing.JPanel Pagina2;
    private javax.swing.JPanel Pagina3;
    private javax.swing.JPanel Pagina4;
    private javax.swing.JTextArea TextAbout;
    private javax.swing.JLabel TextBienv;
    private javax.swing.JTextArea Textpag1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel exitBtn1;
    private javax.swing.JPanel exitBtn2;
    private javax.swing.JPanel exitBtn3;
    private javax.swing.JPanel exitBtn4;
    private javax.swing.JLabel exitTxt1;
    private javax.swing.JLabel exitTxt2;
    private javax.swing.JLabel exitTxt3;
    private javax.swing.JLabel exitTxt4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    // End of variables declaration//GEN-END:variables
}
